# Version of compose
version: "3.9"

# Services that we have
services:
  # The rest api we have build
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: album-api
    environment:
      - POSTGRES_URL=postgres://root:secret@db/recordings?sslmode=disable
    ports:
      - "4000:4000"
    depends_on:
      - db
      - cache
    networks:
      - mynet
    stdin_open: true # docker run -i
    tty: true # docker run -t
  # We need postgres
  db:
    image: postgres
    container_name: albums-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=recordings
    networks:
      - mynet
  cache:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    networks:
      - mynet

# Define the networks
networks:
  course_network:
    external: true
    name: course_network
  mynet:
    driver: bridge
